/execute run scoreboard objectives add challengeTimer dummy;
/execute run scoreboard objectives add challengeID dummy;
/execute run scoreboard objectives add random dummy;
/execute run scoreboard objectives add range dummy;
/execute run scoreboard objectives add challengeScore dummy;
/execute run scoreboard objectives add challengeDone dummy;
/execute run scoreboard objectives add jumpBase dummy;
/execute run scoreboard objectives add walkBase dummy;
/execute run scoreboard objectives add sprintBase dummy;
/execute run scoreboard objectives add dropBase dummy;
/execute run scoreboard objectives add damageBase dummy;
/execute run scoreboard objectives add sneakBase dummy;
/execute run scoreboard objectives add fallBase dummy;
/execute run scoreboard objectives add mineStoneBase dummy;
/execute run scoreboard objectives add mineNetherrackBase dummy;
/execute run scoreboard objectives add mineEndStoneBase dummy;
/execute run scoreboard objectives add pickBase dummy;
/execute run scoreboard objectives add jump minecraft.custom:minecraft.jump;
/execute run scoreboard objectives add walk minecraft.custom:minecraft.walk_one_cm;
/execute run scoreboard objectives add sprint minecraft.custom:minecraft.sprint_one_cm;
/execute run scoreboard objectives add drop minecraft.custom:minecraft.drop;
/execute run scoreboard objectives add damage minecraft.custom:minecraft.damage_taken;
/execute run scoreboard objectives add sneak minecraft.custom:minecraft.sneak_time;
/execute run scoreboard objectives add fall minecraft.custom:minecraft.fall_one_cm;
/execute run scoreboard objectives add mineStone minecraft.mined:minecraft.stone;
/execute run scoreboard objectives add mineNetherrack minecraft.mined:minecraft.netherrack;
/execute run scoreboard objectives add mineEndStone minecraft.mined:minecraft.end_stone;
/execute run scoreboard objectives add pickWood minecraft.used:minecraft.wooden_pickaxe;
/execute run scoreboard objectives add pickStone minecraft.used:minecraft.stone_pickaxe;
/execute run scoreboard objectives add pickIron minecraft.used:minecraft.iron_pickaxe;
/execute run scoreboard objectives add pickGold minecraft.used:minecraft.golden_pickaxe;
/execute run scoreboard objectives add pickDiamond minecraft.used:minecraft.diamond_pickaxe;
/execute run scoreboard objectives add pickNetherite minecraft.used:minecraft.netherite_pickaxe;

/execute run scoreboard players set global range 10;
/execute run scoreboard players set @a challengeTimer -400;
/execute run scoreboard players set @a challengeScore 0;
/execute run scoreboard players set @a challengeDone 0;
/execute run scoreboard players set @a jumpBase 0;
/execute run scoreboard players set @a walkBase 0;
/execute run scoreboard players set @a sprintBase 0;
/execute run scoreboard players set @a dropBase 0;
/execute run scoreboard players set @a damageBase 0;
/execute run scoreboard players set @a sneakBase 0;
/execute run scoreboard players set @a fallBase 0;
/execute run scoreboard players set @a mineStoneBase 0;
/execute run scoreboard players set @a mineNetherrackBase 0;
/execute run scoreboard players set @a mineEndStoneBase 0;
/execute run scoreboard players set @a pickBase 0;

/execute at @a run setblock ~ ~-50 ~ minecraft:repeating_command_block[facing=south]{Command:"execute as @a run scoreboard players add @s challengeTimer 1",auto:1b};
/execute at @a run setblock ~ ~-50 ~1 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=1800..}] run scoreboard players set @s challengeTimer 0",auto:1b};

/execute at @a run setblock ~ ~-50 ~2 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] at @s run summon area_effect_cloud ~ ~ ~ {Tags:[\"random_uuid\"]}",auto:1b};
/execute at @a run setblock ~ ~-50 ~3 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] store result score @s random run data get entity @e[type=area_effect_cloud,tag=random_uuid,limit=1] UUID[0] 1",auto:1b};
/execute at @a run setblock ~ ~-50 ~4 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s random %= global range",auto:1b};
/execute at @a run setblock ~ ~-50 ~5 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,random=..-1}] run scoreboard players operation @s random += global range",auto:1b};
/execute at @a run setblock ~ ~-50 ~6 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s challengeID = @s random",auto:1b};
/execute at @a run setblock ~ ~-50 ~7 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players set @s challengeScore 0",auto:1b};
/execute at @a run setblock ~ ~-50 ~8 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players set @s challengeDone 0",auto:1b};
/execute at @a run setblock ~ ~-50 ~9 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s jumpBase = @s jump",auto:1b};
/execute at @a run setblock ~ ~-50 ~10 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s walkBase = @s walk",auto:1b};
/execute at @a run setblock ~ ~-50 ~11 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s sprintBase = @s sprint",auto:1b};
/execute at @a run setblock ~ ~-50 ~12 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s dropBase = @s drop",auto:1b};
/execute at @a run setblock ~ ~-50 ~13 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s damageBase = @s damage",auto:1b};
/execute at @a run setblock ~ ~-50 ~14 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s sneakBase = @s sneak",auto:1b};
/execute at @a run setblock ~ ~-50 ~15 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s fallBase = @s fall",auto:1b};
/execute at @a run setblock ~ ~-50 ~16 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s mineStoneBase = @s mineStone",auto:1b};
/execute at @a run setblock ~ ~-50 ~17 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s mineNetherrackBase = @s mineNetherrack",auto:1b};
/execute at @a run setblock ~ ~-50 ~18 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s mineEndStoneBase = @s mineEndStone",auto:1b};
/execute at @a run setblock ~ ~-50 ~19 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s pickBase = @s pickWood",auto:1b};
/execute at @a run setblock ~ ~-50 ~20 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s pickBase += @s pickStone",auto:1b};
/execute at @a run setblock ~ ~-50 ~21 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s pickBase += @s pickIron",auto:1b};
/execute at @a run setblock ~ ~-50 ~22 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s pickBase += @s pickGold",auto:1b};
/execute at @a run setblock ~ ~-50 ~23 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s pickBase += @s pickDiamond",auto:1b};
/execute at @a run setblock ~ ~-50 ~24 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run scoreboard players operation @s pickBase += @s pickNetherite",auto:1b};
/execute at @a run setblock ~ ~-50 ~25 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] at @s run kill @e[type=area_effect_cloud,tag=random_uuid,distance=..5]",auto:1b};

/execute at @a run setblock ~ ~-50 ~26 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0}] run playsound minecraft:block.note_block.pling master @a ~ ~ ~ 0.9 1.4",auto:1b};
/execute at @a run setblock ~ ~-50 ~27 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=0}] run title @s title {\"text\":\"!\",\"color\":\"green\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~28 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=0}] run title @s subtitle {\"text\":\"Jump 20 Times\",\"color\":\"green\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~29 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=1}] run title @s title {\"text\":\"!\",\"color\":\"aqua\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~30 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=1}] run title @s subtitle {\"text\":\"Jump 50 Times\",\"color\":\"aqua\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~31 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=2}] run title @s title {\"text\":\"!\",\"color\":\"yellow\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~32 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=2}] run title @s subtitle {\"text\":\"Drop 5 Items\",\"color\":\"yellow\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~33 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=3}] run title @s title {\"text\":\"!\",\"color\":\"red\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~34 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=3}] run title @s subtitle {\"text\":\"Take 3 Hearts Damage\",\"color\":\"red\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~35 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=4}] run title @s title {\"text\":\"!\",\"color\":\"gold\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~36 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=4}] run title @s subtitle {\"text\":\"Take 8 Hearts Damage\",\"color\":\"gold\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~37 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=5}] run title @s title {\"text\":\"!\",\"color\":\"light_purple\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~38 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=5}] run title @s subtitle {\"text\":\"Use Any Pickaxe 8 Times\",\"color\":\"light_purple\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~39 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=6}] run title @s title {\"text\":\"!\",\"color\":\"gray\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~40 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=6}] run title @s subtitle {\"text\":\"Fall 20 Blocks\",\"color\":\"gray\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~41 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=7}] run title @s title {\"text\":\"!\",\"color\":\"white\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~42 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=7}] run title @s subtitle {\"text\":\"Drop 30 Items\",\"color\":\"white\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~43 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=8}] run title @s title {\"text\":\"!\",\"color\":\"dark_green\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~44 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=8},nbt={Dimension:\"minecraft:overworld\"}] run title @s subtitle {\"text\":\"Mine 12 Stone\",\"color\":\"gray\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~45 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=8},nbt={Dimension:\"minecraft:the_nether\"}] run title @s subtitle {\"text\":\"Mine 12 Netherrack\",\"color\":\"red\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~46 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=8},nbt={Dimension:\"minecraft:the_end\"}] run title @s subtitle {\"text\":\"Mine 4 End Stone\",\"color\":\"yellow\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~47 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=9}] run title @s subtitle {\"text\":\"Jump 100 Times\",\"color\":\"red\",\"bold\":true}",auto:1b};
/execute at @a run setblock ~ ~-50 ~48 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=0,challengeID=9}] run title @s title {\"text\":\"!\",\"color\":\"red\",\"bold\":true}",auto:1b};


/execute at @a run setblock ~1 ~-50 ~ minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=0}] run scoreboard players operation @s challengeScore = @s jump",auto:1b};
/execute at @a run setblock ~1 ~-50 ~1 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=0}] run scoreboard players operation @s challengeScore -= @s jumpBase",auto:1b};

/execute at @a run setblock ~2 ~-50 ~ minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=1}] run scoreboard players operation @s challengeScore = @s jump",auto:1b};
/execute at @a run setblock ~2 ~-50 ~1 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=1}] run scoreboard players operation @s challengeScore -= @s jumpBase",auto:1b};
/execute at @a run setblock ~3 ~-50 ~ minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=2}] run scoreboard players operation @s challengeScore = @s drop",auto:1b};
/execute at @a run setblock ~3 ~-50 ~1 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=2}] run scoreboard players operation @s challengeScore -= @s dropBase",auto:1b};
/execute at @a run setblock ~4 ~-50 ~ minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=3}] run scoreboard players operation @s challengeScore = @s damage",auto:1b};
/execute at @a run setblock ~4 ~-50 ~1 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=3}] run scoreboard players operation @s challengeScore -= @s damageBase",auto:1b};
/execute at @a run setblock ~5 ~-50 ~ minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=4}] run scoreboard players operation @s challengeScore = @s damage",auto:1b};
/execute at @a run setblock ~5 ~-50 ~1 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=4}] run scoreboard players operation @s challengeScore -= @s damageBase",auto:1b};
/execute at @a run setblock ~6 ~-50 ~ minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=5}] run scoreboard players operation @s challengeScore = @s pickWood",auto:1b};
/execute at @a run setblock ~6 ~-50 ~1 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=5}] run scoreboard players operation @s challengeScore += @s pickStone",auto:1b};
/execute at @a run setblock ~6 ~-50 ~2 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=5}] run scoreboard players operation @s challengeScore += @s pickIron",auto:1b};
/execute at @a run setblock ~6 ~-50 ~3 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=5}] run scoreboard players operation @s challengeScore += @s pickGold",auto:1b};
/execute at @a run setblock ~6 ~-50 ~4 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=5}] run scoreboard players operation @s challengeScore += @s pickDiamond",auto:1b};
/execute at @a run setblock ~6 ~-50 ~5 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=5}] run scoreboard players operation @s challengeScore += @s pickNetherite",auto:1b};
/execute at @a run setblock ~6 ~-50 ~6 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=5}] run scoreboard players operation @s challengeScore -= @s pickBase",auto:1b};
/execute at @a run setblock ~7 ~-50 ~ minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=6}] run scoreboard players operation @s challengeScore = @s fall",auto:1b};
/execute at @a run setblock ~7 ~-50 ~1 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=6}] run scoreboard players operation @s challengeScore -= @s fallBase",auto:1b};
/execute at @a run setblock ~8 ~-50 ~ minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=7}] run scoreboard players operation @s challengeScore = @s drop",auto:1b};
/execute at @a run setblock ~8 ~-50 ~1 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=7}] run scoreboard players operation @s challengeScore -= @s dropBase",auto:1b};
/execute at @a run setblock ~9 ~-50 ~ minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=8},nbt={Dimension:\"minecraft:overworld\"}] run scoreboard players operation @s challengeScore = @s mineStone",auto:1b};
/execute at @a run setblock ~9 ~-50 ~1 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=8},nbt={Dimension:\"minecraft:overworld\"}] run scoreboard players operation @s challengeScore -= @s mineStoneBase",auto:1b};
/execute at @a run setblock ~10 ~-50 ~ minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=8},nbt={Dimension:\"minecraft:the_nether\"}] run scoreboard players operation @s challengeScore = @s mineNetherrack",auto:1b};
/execute at @a run setblock ~10 ~-50 ~1 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=8},nbt={Dimension:\"minecraft:the_nether\"}] run scoreboard players operation @s challengeScore -= @s mineNetherrackBase",auto:1b};
/execute at @a run setblock ~11 ~-50 ~ minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=8},nbt={Dimension:\"minecraft:the_end\"}] run scoreboard players operation @s challengeScore = @s mineEndStone",auto:1b};
/execute at @a run setblock ~11 ~-50 ~1 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=8},nbt={Dimension:\"minecraft:the_end\"}] run scoreboard players operation @s challengeScore -= @s mineEndStoneBase",auto:1b};
/execute at @a run setblock ~12 ~-50 ~ minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=9}] run scoreboard players operation @s challengeScore = @s jump",auto:1b};
/execute at @a run setblock ~12 ~-50 ~1 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=9}] run scoreboard players operation @s challengeScore -= @s jumpBase",auto:1b};


/execute at @a run setblock ~1 ~-50 ~8 minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=0,challengeDone=0,challengeScore=20..}] run tellraw @s {\"text\":\"Challenge complete!\",\"color\":\"green\"}",auto:1b};
/execute at @a run setblock ~1 ~-50 ~9 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=0,challengeDone=0,challengeScore=20..}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 0.8 1.2",auto:1b};
/execute at @a run setblock ~1 ~-50 ~10 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=0,challengeDone=0,challengeScore=20..}] run scoreboard players set @s challengeDone 1",auto:1b};
/execute at @a run setblock ~2 ~-50 ~8 minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=1,challengeDone=0,challengeScore=40..}] run tellraw @s {\"text\":\"Challenge complete!\",\"color\":\"green\"}",auto:1b};
/execute at @a run setblock ~2 ~-50 ~9 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=1,challengeDone=0,challengeScore=40..}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 0.8 1.2",auto:1b};
/execute at @a run setblock ~2 ~-50 ~10 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=1,challengeDone=0,challengeScore=40..}] run scoreboard players set @s challengeDone 1",auto:1b};
/execute at @a run setblock ~3 ~-50 ~8 minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=2,challengeDone=0,challengeScore=5..}] run tellraw @s {\"text\":\"Challenge complete!\",\"color\":\"green\"}",auto:1b};
/execute at @a run setblock ~3 ~-50 ~9 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=2,challengeDone=0,challengeScore=5..}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 0.8 1.2",auto:1b};
/execute at @a run setblock ~3 ~-50 ~10 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=2,challengeDone=0,challengeScore=5..}] run scoreboard players set @s challengeDone 1",auto:1b};
/execute at @a run setblock ~4 ~-50 ~8 minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=3,challengeDone=0,challengeScore=30..}] run tellraw @s {\"text\":\"Challenge complete!\",\"color\":\"green\"}",auto:1b};
/execute at @a run setblock ~4 ~-50 ~9 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=3,challengeDone=0,challengeScore=30..}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 0.8 1.2",auto:1b};
/execute at @a run setblock ~4 ~-50 ~10 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=3,challengeDone=0,challengeScore=30..}] run scoreboard players set @s challengeDone 1",auto:1b};
/execute at @a run setblock ~5 ~-50 ~8 minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=4,challengeDone=0,challengeScore=80..}] run tellraw @s {\"text\":\"Challenge complete!\",\"color\":\"green\"}",auto:1b};
/execute at @a run setblock ~5 ~-50 ~9 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=4,challengeDone=0,challengeScore=80..}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 0.8 1.2",auto:1b};
/execute at @a run setblock ~5 ~-50 ~10 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=4,challengeDone=0,challengeScore=80..}] run scoreboard players set @s challengeDone 1",auto:1b};
/execute at @a run setblock ~6 ~-50 ~8 minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=5,challengeDone=0,challengeScore=8..}] run tellraw @s {\"text\":\"Challenge complete!\",\"color\":\"green\"}",auto:1b};
/execute at @a run setblock ~6 ~-50 ~9 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=5,challengeDone=0,challengeScore=8..}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 0.8 1.2",auto:1b};
/execute at @a run setblock ~6 ~-50 ~10 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=5,challengeDone=0,challengeScore=8..}] run scoreboard players set @s challengeDone 1",auto:1b};
/execute at @a run setblock ~7 ~-50 ~8 minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=6,challengeDone=0,challengeScore=2000..}] run tellraw @s {\"text\":\"Challenge complete!\",\"color\":\"green\"}",auto:1b};
/execute at @a run setblock ~7 ~-50 ~9 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=6,challengeDone=0,challengeScore=2000..}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 0.8 1.2",auto:1b};
/execute at @a run setblock ~7 ~-50 ~10 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=6,challengeDone=0,challengeScore=2000..}] run scoreboard players set @s challengeDone 1",auto:1b};
/execute at @a run setblock ~8 ~-50 ~8 minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=7,challengeDone=0,challengeScore=30..}] run tellraw @s {\"text\":\"Challenge complete!\",\"color\":\"green\"}",auto:1b};
/execute at @a run setblock ~8 ~-50 ~9 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=7,challengeDone=0,challengeScore=30..}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 0.8 1.2",auto:1b};
/execute at @a run setblock ~8 ~-50 ~10 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=7,challengeDone=0,challengeScore=30..}] run scoreboard players set @s challengeDone 1",auto:1b};

/execute at @a run setblock ~9 ~-50 ~8 minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=8,challengeDone=0,challengeScore=12..}] run tellraw @s {\"text\":\"Challenge complete!\",\"color\":\"green\"}",auto:1b};
/execute at @a run setblock ~9 ~-50 ~9 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=8,challengeDone=0,challengeScore=12..}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 0.8 1.2",auto:1b};
/execute at @a run setblock ~9 ~-50 ~10 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=8,challengeDone=0,challengeScore=12..}] run scoreboard players set @s challengeDone 1",auto:1b};

/execute at @a run setblock ~10 ~-50 ~8 minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeID=9,challengeDone=0,challengeScore=100..}] run tellraw @s {\"text\":\"Challenge complete!\",\"color\":\"green\"}",auto:1b};
/execute at @a run setblock ~10 ~-50 ~9 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=9,challengeDone=0,challengeScore=100..}] run playsound minecraft:entity.player.levelup master @a ~ ~ ~ 0.8 1.2",auto:1b};
/execute at @a run setblock ~10 ~-50 ~10 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeID=9,challengeDone=0,challengeScore=100..}] run scoreboard players set @s challengeDone 1",auto:1b};

/execute at @a run setblock ~11 ~-50 ~8 minecraft:repeating_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=600,challengeDone=0}] run tellraw @s {\"text\":\"Challenge failed. You were too slow.\",\"color\":\"red\"}",auto:1b};
/execute at @a run setblock ~11 ~-50 ~9 minecraft:chain_command_block[facing=south]{Command:"execute as @a[scores={challengeTimer=600,challengeDone=0}] run kill @s",auto:1b};

/execute at @a run tellraw @a ["",{"text":"MCSR Ranked Says","bold":true,"color":"gold"},{"text":"\nEvery 90 seconds, a random task appears. You have 30 seconds or you die.","color":"aqua"}];