/execute at @a run setblock ~ ~-50 ~ repeating_command_block[facing=up]{Command:"execute in minecraft:overworld as @a[nbt={Dimension:\"minecraft:overworld\"}] if entity @s[distance=..120] run clear @s",auto:1b};
/execute at @a run setblock ~1 ~-50 ~ repeating_command_block[facing=up]{Command:"execute in minecraft:overworld as @a[nbt={Dimension:\"minecraft:overworld\"}] if entity @s[distance=..120] run tp @s ~1 231 ~",auto:1b};
/execute at @a run fill ~23 230 ~-2 ~18 227 ~2 stone;
/execute at @a run setblock ~22 231 ~-1 iron_ore;
/execute at @a run setblock ~19 231 ~0 iron_ore;
/execute at @a run setblock ~21 231 ~1 iron_ore;
/execute at @a run setblock ~19 231 ~-1 iron_ore;
/execute at @a run setblock ~18 231 ~-2 gravel;
/execute at @a run setblock ~23 231 ~0 gravel;
/execute at @a run setblock ~20 231 ~2 gravel;
/execute at @a run fill ~-3 230 ~-2 ~2 228 ~2 grass_block;
/execute at @a run fill ~-2 230 ~30 ~2 228 ~34 netherrack;
/execute at @a run setblock ~ 229 ~31 obsidian;
/execute at @a run setblock ~ 230 ~31 obsidian;
/execute at @a run setblock ~ 231 ~31 obsidian;
/execute at @a run setblock ~ 232 ~31 obsidian;
/execute at @a run setblock ~ 233 ~31 obsidian;
/execute at @a run setblock ~ 229 ~32 obsidian;
/execute at @a run setblock ~ 229 ~33 obsidian;
/execute at @a run setblock ~ 229 ~33 obsidian;
/execute at @a run setblock ~ 233 ~32 obsidian;
/execute at @a run setblock ~ 233 ~33 obsidian;
/execute at @a run setblock ~ 233 ~34 obsidian;
/execute at @a run setblock ~ 230 ~34 obsidian;
/execute at @a run setblock ~ 231 ~34 obsidian;
/execute at @a run setblock ~ 232 ~34 obsidian;
/gamerule spawnRadius 6;
/setworldspawn ~ ~230 ~;
/execute at @a run tp @s ~2 230 ~;
/execute at @a run give @s oak_sapling 2;
/execute at @a run give @s bone_meal 32;
/execute at @a run give @s lava_bucket 1;
/execute at @a run give @s ice 1;
/execute at @a run give @s carrot 6;
/tellraw @a ["",{"text":"Skyblock!","color":"green","bold":true},{"text":"\n"},{"text":"You have the basic items","color":"yellow"},{"text":"\n"}];